### ISSUE TITLE
README: Clarify that <table> within component is the data table

### ISSUE THREAD

**Issue by menewman** [MyPureCloud/ember-multi-faceted-search#3]
This wasn't obvious to me on first read (in the **Using this addon** / **The Component** section). I thought it might be a table meant to represent facets, rather than the actual data being filtered.

```hbs
{{#multi-faceted-search facets=yourFacetsArray addFacet=(action 'yourAddFacetAction') removeFacet=(action 'yourRemoveFacetAction')}}
<table>
...
</table>
{{/multi-faceted-search}}
```

**Comment by smargovsky** [comment]
Done in version 0.1.0 and up.
