### ISSUE TITLE
Simplify conditions in facet.js / selectedValues

### ISSUE THREAD

**Issue by menewman** [MyPureCloud/ember-multi-faceted-search#5]
In the selectedValues computed property, you could condense the following expression:

```javascript
if (terms.length > 1) {
  return terms.map(t => t.value).join(", ");
} else if (terms.length === 1) {
  return terms[0].value;
} else {
  return "";
}
```

The special check for `terms.length === 1` is unnecessary because `terms.map(t => t.value).join(", ")` will yield the same result as `terms[0].value` when terms has a length of 1. So, you could omit the second case and just have the first condition apply if `terms.length > 0`.

**Comment by smargovsky** [comment]
Done
